version: '3'
services:
  mysql:
    image: mysql:5.6.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "meli"
    networks:
      meli:
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - meli
  python2.7.2:
    depends_on:
      - mysql
    build: .
    command: python -u santi.py
    links:
      - mysql:db
    networks:
      - meli
networks:
  meli:
      
  