version: '3'
services:
  mysql:
    image: mysql:5.6.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "meli"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      meli:
  phpmyadmin1:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - meli
  python:
    depends_on:
      - mysql
    build: .
    command: python3 -u quickstart.py
    volumes:
      - .:/meli
    links:
      - mysql:db
    networks:
      - meli
networks:
  meli:
      
  
